services:
  postgres:
    image: postgres:17-alpine
    container_name: ecom-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecom-admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecom-db
    ports:
      - "5432:5432"
    volumes:
      - ecom-data:/var/lib/postgresql/data

volumes:
  ecom-data: